name: CarbonPanda - Home Automation
description: A blog mainly for Home AUtomation.
author: Max
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
